{{- $name := include "sh360-web.fullname" . -}}
{{- $cfgname := include "sh360-config.name" . -}}
{{- $host := index .Values.ingress.hosts 0 -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "sh360-web.name" . }}
    chart: {{ template "sh360-web.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ApplicationInsights__InstrumentationKey:  {{ .Values.appinsights.id }}
  SettingsUrl: http://{{ $cfgname }}/cfg/aks
  urls__hotels: http://{{ $host }}/hotels-api/
  urls__bookings: http://{{ $host }}/bookings/
  urls__suggestions: http://{{ $host }}/suggestions-api/
  urls__tasks: http://{{ $host }}/tasks-api/
  urls__notifications: http://{{ $host }}/notifications-api/
  urls__reviews: http://{{ $host }}/reviews-api/
  urls__discounts: http://{{ $host }}/discounts-api/
  urls__images_base: {{ .Values.urls.images }}
# PetsConfig configuration
  petsconfig__blobName: {{ .Values.petsconfig.blobname }}
  petsconfig__blobKey: {{ .Values.petsconfig.blobkey }}
  petsconfig__cosmosUri: {{ .Values.petsconfig.cosmosuri }}
  petsconfig__cosmosKey: {{ .Values.petsconfig.cosmoskey }}
  petsconfig__api: {{ .Values.petsconfig.api }}
# FakeAuth configuration
  fakeauth__name: {{ .Values.fakeauth.name }}
  fakeauth__picurl: {{ .Values.fakeauth.picurl }}
  fakeauth__userid: {{ .Values.fakeauth.userid }}